### ISSUE TITLE
iw repository is inaccessible on m6.0.1_1.0.0_variscite

### ISSUE THREAD

**Issue by steven-joruk** [varigit/MX6-marshmallow-AFS#1]
sig.sipsolutions.net is down, this means running variscite/install results in your working tree needing to be manually fixed because the install script can't handle re-running.

A good mirror to use is `https://kernel.googlesource.com/pub/scm/linux/kernel/git/jberg/iw`

**Comment by eranmati** [comment]
Hi Steven.
This is already fixed on the m6.0.1_2.1.0-ga-var01 branch.
I've just applied the same fix to m6.0.1_1.0.0_variscite.
You may want to consider upgrading to our latest Android anyway (see: http://variwiki.com/index.php?title=VAR-SOM-MX6_Android_M6.0.1_2.1.0).

Thanks,
Eran
