### ISSUE TITLE
The install program does not work (m6.0.1_2.1.0-ga-var01)

### ISSUE THREAD

**Issue by DenisN03** [varigit/MX6-marshmallow-AFS#2]
When the program starts, an error occurs due to the absence of the commit 4ba8edfbd44814d2e2c7b8167401344ddd8f2736. How to fix this problem? Where can I find this commit?

**Comment by eranmati** [comment]
Hi @DenisN03 .
This commit is present in the following ti git:
git://git.omapzoom.org/platform/hardware/ti/wlan.git
I've just verified it works.

Please check your Internet connection and firewall.

Next time, please open a support ticket via Variscite's customer portal:
http://www.variscite.com/support/variscite-customer-portal

Regards,
Eran
